default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima39983_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: afurima39983_test


production:
  <<: *default
  database: furima_39983_production
  username: furima_39983
  password: <%= ENV["FURIMA_39983_DATABASE_PASSWORD"] %>
